// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw1o65g0dXY3GFCCLDcbY6PlWNP_2O3HM',
    appId: '1:127595182959:web:c820ae2f2dd1b1acb8469a',
    messagingSenderId: '127595182959',
    projectId: 'healthmate-1c9c6',
    authDomain: 'healthmate-1c9c6.firebaseapp.com',
    storageBucket: 'healthmate-1c9c6.appspot.com',
    measurementId: 'G-16NV3BBTVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg5QuSwIuQhFhf8Q2Z2UXRtYfZoSEcvC0',
    appId: '1:127595182959:android:0e5cedee5e14828cb8469a',
    messagingSenderId: '127595182959',
    projectId: 'healthmate-1c9c6',
    storageBucket: 'healthmate-1c9c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoPzeRgeujHY-IZ0h6zLRwMIYoaEpBXW4',
    appId: '1:127595182959:ios:7f9509b77231586bb8469a',
    messagingSenderId: '127595182959',
    projectId: 'healthmate-1c9c6',
    storageBucket: 'healthmate-1c9c6.appspot.com',
    iosBundleId: 'com.tos.healthmate.healthmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoPzeRgeujHY-IZ0h6zLRwMIYoaEpBXW4',
    appId: '1:127595182959:ios:eee8523173a0af3fb8469a',
    messagingSenderId: '127595182959',
    projectId: 'healthmate-1c9c6',
    storageBucket: 'healthmate-1c9c6.appspot.com',
    iosBundleId: 'com.tos.healthmate.healthmate.RunnerTests',
  );
}
